config/routes.rb
Goals::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'welcome#index'

  get '/load' => 'life#load'
  post '/save' => 'life#save'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  get '/goals', to: 'goals#index'
  get '/about', to: 'welcome#about'

  resources :sessions, only: [:new, :create]
  resources :users

end

app/models/life.rb
class Life
  include Mongoid::Document
  field :maxId,       type: Integer
  field :goals,       type: Array
  field :connections, type: Array
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: true, uniqueness: true
  validates :password, length: { in: 6..20 }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  has_secure_password

  before_create :create_life

  def create_life
    @life = Life.create
    self.life_id = @life.id.to_s
  end

  def life
    Life.find(self.life_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    if current_user
      @goals = GoalsPresenter.new(current_user)
      @titles = @goals.title_words
      @reflections = @goals.reflection_words
      @title_string = @goals.title_string
      render "index"
    else
      redirect_to root_path
    end
  end

end

app/controllers/life_controller.rb
class LifeController < ApplicationController
  respond_to :json

  def save
    @life = Life.find(current_user.life_id)
    @life.update(params[:life_data])
    @life.save!
    render nothing: true
  end

  def load
    @life = Life.find(current_user.life_id)
    render json: @life
  end

  # Refactor to include this method so we can re-enanble strong pararms
  def permit_params
    params[:life_data].require(:life).permit(:maxId, :goals, :connections)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:signin_error] = "Invalid Email or Password. Please try again."
      redirect_to new_session_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def landing_page
    @disable_nav = true
  end

  private
  def create_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    landing_page
    redirect_to root_path # ??
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render new_user_path
    end
  end

  def show
    redirect_to root_path
  end

  def landing_page
    @disable_nav = true
  end

  private
  def create_params
    params.require(:user).permit(:email, :password, :password_confirmation, :birthday)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goals/index.html.erb
<div class="container">
<style>
  #words {
    position: absolute;
    margin-left: 240px;
    top: 80px;
  }
  #themes {
    font-size: 1.5em;
    position: absolute;
    margin-left: 120px;
    color: #F0EBDF;
  }
  #description {
    margin-top: -70px;
    margin-left: 270px;
    color: #343434;
    float: right;
  }
  #empty {
    color: #343434;
    position: absolute;
    margin-left: 270px;
    top: 250px
  }
  #inspire {
    color: #08FF8D;
  }
  #g {
    float: right;
  }
</style>

<p id="titles"><%= @title_string %></p>

<div id="themes"><br><br><h1>Goal Cloud:</h1><h4 id="description">a sampling of words from your LifeBar goals. What do you see?</h4></div>

<div id="words"></div>

<div id="empty"><h3>Hmmmm ... looks like you have not created any goals. Why don't you start?
  <br><br><br>
  <blockquote><span id="inspire">"Glory lies in the attempt to reach one's goal and not in reaching it."</span></blockquote>
  <span id="g">- Mahatma Gandhi</span></h3></div>

<script src= "//cdnjs.cloudflare.com/ajax/libs/d3/3.4.2/d3.min.js" type="text/javascript"></script>

<script type="text/javascript">


$("#titles").hide();
$("#empty").hide();

// Create word array from goal words

var allWords = $("#titles").text().trim().split(" ");

// Hide words div if no goals have been set yet

if (allWords.join("") === "Youhavenogoals" ) {
  $("#words").hide();
  $("#empty").show();
}

// Word Cloud Algorithm

(function(exports) {
  function cloud() {
    var size = [256, 256],
        text = cloudText,
        font = cloudFont,
        fontSize = cloudFontSize,
        rotate = cloudRotate,
        padding = cloudPadding,
        spiral = archimedeanSpiral,
        words = [],
        timeInterval = Infinity,
        event = d3.dispatch("word", "end"),
        timer = null,
        cloud = {};

    cloud.start = function() {
      var board = zeroArray((size[0] >> 5) * size[1]),
          bounds = null,
          n = words.length,
          i = -1,
          tags = [],
          data = words.map(function(d, i) {
        return {
          text: text.call(this, d, i),
          font: font.call(this, d, i),
          rotate: rotate.call(this, d, i),
          size: ~~fontSize.call(this, d, i),
          padding: cloudPadding.call(this, d, i)
        };
      }).sort(function(a, b) { return b.size - a.size; });

      if (timer) clearInterval(timer);
      timer = setInterval(step, 0);
      step();

      return cloud;

      function step() {
        var start = +new Date,
            d;
        while (+new Date - start < timeInterval && ++i < n && timer) {
          d = data[i];
          d.x = (size[0] * (Math.random() + .5)) >> 1;
          d.y = (size[1] * (Math.random() + .5)) >> 1;
          cloudSprite(d, data, i);
          if (place(board, d, bounds)) {
            tags.push(d);
            event.word(d);
            if (bounds) cloudBounds(bounds, d);
            else bounds = [{x: d.x + d.x0, y: d.y + d.y0}, {x: d.x + d.x1, y: d.y + d.y1}];
            // Temporary hack
            d.x -= size[0] >> 1;
            d.y -= size[1] >> 1;
          }
        }
        if (i >= n) {
          cloud.stop();
          event.end(tags, bounds);
        }
      }
    }

    cloud.stop = function() {
      if (timer) {
        clearInterval(timer);
        timer = null;
      }
      return cloud;
    };

    cloud.timeInterval = function(x) {
      if (!arguments.length) return timeInterval;
      timeInterval = x == null ? Infinity : x;
      return cloud;
    };

    function place(board, tag, bounds) {
      var perimeter = [{x: 0, y: 0}, {x: size[0], y: size[1]}],
          startX = tag.x,
          startY = tag.y,
          maxDelta = Math.sqrt(size[0] * size[0] + size[1] * size[1]),
          s = spiral(size),
          dt = Math.random() < .5 ? 1 : -1,
          t = -dt,
          dxdy,
          dx,
          dy;

      while (dxdy = s(t += dt)) {
        dx = ~~dxdy[0];
        dy = ~~dxdy[1];

        if (Math.min(dx, dy) > maxDelta) break;

        tag.x = startX + dx;
        tag.y = startY + dy;

        if (tag.x + tag.x0 < 0 || tag.y + tag.y0 < 0 ||
            tag.x + tag.x1 > size[0] || tag.y + tag.y1 > size[1]) continue;
        // TODO only check for collisions within current bounds.
        if (!bounds || !cloudCollide(tag, board, size[0])) {
          if (!bounds || collideRects(tag, bounds)) {
            var sprite = tag.sprite,
                w = tag.width >> 5,
                sw = size[0] >> 5,
                lx = tag.x - (w << 4),
                sx = lx & 0x7f,
                msx = 32 - sx,
                h = tag.y1 - tag.y0,
                x = (tag.y + tag.y0) * sw + (lx >> 5),
                last;
            for (var j = 0; j < h; j++) {
              last = 0;
              for (var i = 0; i <= w; i++) {
                board[x + i] |= (last << msx) | (i < w ? (last = sprite[j * w + i]) >>> sx : 0);
              }
              x += sw;
            }
            delete tag.sprite;
            return true;
          }
        }
      }
      return false;
    }

    cloud.words = function(x) {
      if (!arguments.length) return words;
      words = x;
      return cloud;
    };

    cloud.size = function(x) {
      if (!arguments.length) return size;
      size = [+x[0], +x[1]];
      return cloud;
    };

    cloud.font = function(x) {
      if (!arguments.length) return font;
      font = d3.functor(x);
      return cloud;
    };

    cloud.rotate = function(x) {
      if (!arguments.length) return rotate;
      rotate = d3.functor(x);
      return cloud;
    };

    cloud.text = function(x) {
      if (!arguments.length) return text;
      text = d3.functor(x);
      return cloud;
    };

    cloud.spiral = function(x) {
      if (!arguments.length) return spiral;
      spiral = spirals[x + ""] || x;
      return cloud;
    };

    cloud.fontSize = function(x) {
      if (!arguments.length) return fontSize;
      fontSize = d3.functor(x);
      return cloud;
    };

    cloud.padding = function(x) {
      if (!arguments.length) return padding;
      padding = d3.functor(x);
      return cloud;
    };

    return d3.rebind(cloud, event, "on");
  }

  function cloudText(d) {
    return d.text;
  }

  function cloudFont() {
    return "serif";
  }

  function cloudFontSize(d) {
    return Math.sqrt(d.value);
  }

  function cloudRotate() {
    return (~~(Math.random() * 6) - 3) * 30;
  }

  function cloudPadding() {
    return 1;
  }

  // Fetches a monochrome sprite bitmap for the specified text.
  // Load in batches for speed.
  function cloudSprite(d, data, di) {
    if (d.sprite) return;
    c.clearRect(0, 0, (cw << 5) / ratio, ch / ratio);
    var x = 0,
        y = 0,
        maxh = 0,
        n = data.length;
    di--;
    while (++di < n) {
      d = data[di];
      c.save();
      c.font = ~~((d.size + 1) / ratio) + "px " + d.font;
      var w = c.measureText(d.text + "m").width * ratio,
          h = d.size << 1;
      if (d.rotate) {
        var sr = Math.sin(d.rotate * cloudRadians),
            cr = Math.cos(d.rotate * cloudRadians),
            wcr = w * cr,
            wsr = w * sr,
            hcr = h * cr,
            hsr = h * sr;
        w = (Math.max(Math.abs(wcr + hsr), Math.abs(wcr - hsr)) + 0x1f) >> 5 << 5;
        h = ~~Math.max(Math.abs(wsr + hcr), Math.abs(wsr - hcr));
      } else {
        w = (w + 0x1f) >> 5 << 5;
      }
      if (h > maxh) maxh = h;
      if (x + w >= (cw << 5)) {
        x = 0;
        y += maxh;
        maxh = 0;
      }
      if (y + h >= ch) break;
      c.translate((x + (w >> 1)) / ratio, (y + (h >> 1)) / ratio);
      if (d.rotate) c.rotate(d.rotate * cloudRadians);
      c.fillText(d.text, 0, 0);
      c.restore();
      d.width = w;
      d.height = h;
      d.xoff = x;
      d.yoff = y;
      d.x1 = w >> 1;
      d.y1 = h >> 1;
      d.x0 = -d.x1;
      d.y0 = -d.y1;
      x += w;
    }
    var pixels = c.getImageData(0, 0, (cw << 5) / ratio, ch / ratio).data,
        sprite = [];
    while (--di >= 0) {
      d = data[di];
      var w = d.width,
          w32 = w >> 5,
          h = d.y1 - d.y0,
          p = d.padding;
      // Zero the buffer
      for (var i = 0; i < h * w32; i++) sprite[i] = 0;
      x = d.xoff;
      if (x == null) return;
      y = d.yoff;
      var seen = 0,
          seenRow = -1;
      for (var j = 0; j < h; j++) {
        for (var i = 0; i < w; i++) {
          var k = w32 * j + (i >> 5),
              m = pixels[((y + j) * (cw << 5) + (x + i)) << 2] ? 1 << (31 - (i % 32)) : 0;
          if (p) {
            if (j) sprite[k - w32] |= m;
            if (j < w - 1) sprite[k + w32] |= m;
            m |= (m << 1) | (m >> 1);
          }
          sprite[k] |= m;
          seen |= m;
        }
        if (seen) seenRow = j;
        else {
          d.y0++;
          h--;
          j--;
          y++;
        }
      }
      d.y1 = d.y0 + seenRow;
      d.sprite = sprite.slice(0, (d.y1 - d.y0) * w32);
    }
  }

  // Use mask-based collision detection.
  function cloudCollide(tag, board, sw) {
    sw >>= 5;
    var sprite = tag.sprite,
        w = tag.width >> 5,
        lx = tag.x - (w << 4),
        sx = lx & 0x7f,
        msx = 32 - sx,
        h = tag.y1 - tag.y0,
        x = (tag.y + tag.y0) * sw + (lx >> 5),
        last;
    for (var j = 0; j < h; j++) {
      last = 0;
      for (var i = 0; i <= w; i++) {
        if (((last << msx) | (i < w ? (last = sprite[j * w + i]) >>> sx : 0))
            & board[x + i]) return true;
      }
      x += sw;
    }
    return false;
  }

  function cloudBounds(bounds, d) {
    var b0 = bounds[0],
        b1 = bounds[1];
    if (d.x + d.x0 < b0.x) b0.x = d.x + d.x0;
    if (d.y + d.y0 < b0.y) b0.y = d.y + d.y0;
    if (d.x + d.x1 > b1.x) b1.x = d.x + d.x1;
    if (d.y + d.y1 > b1.y) b1.y = d.y + d.y1;
  }

  function collideRects(a, b) {
    return a.x + a.x1 > b[0].x && a.x + a.x0 < b[1].x && a.y + a.y1 > b[0].y && a.y + a.y0 < b[1].y;
  }

  function archimedeanSpiral(size) {
    var e = size[0] / size[1];
    return function(t) {
      return [e * (t *= .1) * Math.cos(t), t * Math.sin(t)];
    };
  }

  function rectangularSpiral(size) {
    var dy = 4,
        dx = dy * size[0] / size[1],
        x = 0,
        y = 0;
    return function(t) {
      var sign = t < 0 ? -1 : 1;
      // See triangular numbers: T_n = n * (n + 1) / 2.
      switch ((Math.sqrt(1 + 4 * sign * t) - sign) & 3) {
        case 0:  x += dx; break;
        case 1:  y += dy; break;
        case 2:  x -= dx; break;
        default: y -= dy; break;
      }
      return [x, y];
    };
  }

  function zeroArray(n) {
    var a = [],
        i = -1;
    while (++i < n) a[i] = 0;
    return a;
  }

  var cloudRadians = Math.PI / 180,
      cw = 1 << 11 >> 5,
      ch = 1 << 11,
      canvas,
      ratio = 1;

  if (typeof document !== "undefined") {
    canvas = document.createElement("canvas");
    canvas.width = 1;
    canvas.height = 1;
    ratio = Math.sqrt(canvas.getContext("2d").getImageData(0, 0, 1, 1).data.length >> 2);
    canvas.width = (cw << 5) / ratio;
    canvas.height = ch / ratio;
  } else {
    // node-canvas support
    var Canvas = require("canvas");
    canvas = new Canvas(cw << 5, ch);
  }

  var c = canvas.getContext("2d"),
      spirals = {
        archimedean: archimedeanSpiral,
        rectangular: rectangularSpiral
      };
  c.fillStyle = "red";
  c.textAlign = "center";

  exports.cloud = cloud;
})(typeof exports === "undefined" ? d3.layout || (d3.layout = {}) : exports);

// Customize word cloud

 var fill = d3.scale.category20();
 var fillColor = d3.scale.ordinal().range(['#FF530D', '#08FF8D', '#110CE8']);

  d3.layout.cloud().size([700, 500])
      .words(allWords.map(function(d) {
        return {text: d, size: 10 + Math.random() * 50};
      }))
      .rotate(function() { return ~~(Math.random() * 2) * 90; })
      .font("Impact")
      .fontSize(function(d) { return d.size * 3.5; })
      .on("end", draw)
      .start();

  function draw(words) {
    d3.select("#words").append("svg")
        .attr("width", 800)
        .attr("height", 800)
      .append("g")
        .attr("transform", "translate(400,400)")
      .selectAll("text")
        .data(words)
      .enter().append("text")
        .style("font-size", function(d) { return d.size + "px"; })
        .style("font-family", "Impact")
        .style("fill", function(d) { return fillColor(d.text.toLowerCase()); })
        .attr("text-anchor", "middle")
        .attr("text-align", "center")
        .attr("transform", function(d) {
          return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
        })
        .text(function(d) { return d.text; });
  }
</script>

</div>

app/views/layouts/_navbar.html.erb
<div id="title-nav">
  <div id="nav-left">
    <%= link_to image_tag("/lifeBar_icon.png", :alt => ''), root_path, :class => 'logo' %>
  </div>
  <div id="nav-right">
    <ul>
      <li id="about">
        <a href="/about">About</a>
      </li>

      <% if current_user %>
        <li id="signin">
          <%= link_to "Sign Out", signout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", signin_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
      <% end %>

    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>lifeBar</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="lifeBar_ico.png" type="image/x-icon">
  <link rel="icon" href="lifeBar_ico.png" type="image/x-icon">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:300' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render partial: "layouts/navbar" unless @disable_nav %>
  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<div id="container">
  <%= form_for(@user) do |f| %>
    <h2>Sign Up</h2>
    <p>
      <%= f.label(:email, "Email:") %>
      <%= f.text_field(:email, placeholder: 'me@lifegoals.edu') %><br><br>

      <%= f.label(:password, "Password:") %>
      <%= f.password_field(:password, placeholder: "6 to 20 characters") %><br><br>

      <%= f.label(:password_confirmation, "Confirm password:") %>
      <%= f.password_field(:password_confirmation, placeholder: "6 to 20 characters") %><br><br>

      <%= f.label(:birthday, "Birthday:") %>
      <%= date_select :user, 
                      :birthday, 
                      start_year: (Time.now.year - 5), 
                      end_year: (Time.now.year - 80) %>
    <br><br>
    </p>
      <%= f.submit("Sign Up") %>
  <% end %>


  <div class="signup_error">
    <% if @user.errors.any? %>
      <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    <% end %>
  </div>

</div>

app/views/welcome/_loadlifedata.html.erb
<div id='logged-in'>
  <div id="birthday" data-birthday="<%= current_user.birthday %>">
  </div>
</div >

app/views/welcome/about.html.erb
<br><br><br><br>
<div id="content">
<h3 id="quote"><blockquote>"A goal is not always meant to be <span id="first">reached</span>, it often serves simply as something to <span id="last">aim</span> at."</blockquote> <p style="text-align: center">- Bruce Lee</p></h3>
<br>

<h1 class="about question">What is LifeBar?</h1>

<p class="about text">LifeBar is not a task list, it is not a calendar, it is not a reminder tool. LifeBar is the place to store things that you want to do, not the things that you have to do.</p>

<p class="about text">Rather than placing goals in rigid time slots that are forgotten when that time has come and gone, LifeBar invites you to place goals onto your LifeBar in either the past, present, or future. These goals are always present on the LifeBar until the time that you decide to remove them.</p>

<p class="about text">LifeBar goals do not exist in isolation, they can be connected, moved, and marked as complete. If a goal is completed, you are asked to reflect on the goal. LifeBar can thematically cluster your goals too.</p>

<p class="about text">Goals are more than a thing, they are a part of your life journey. Creating goals, completing (or not completing) goals, and reflecting on goals allows you to visualize goals as they are meaningful to you.</p>

<h1 class="about question">How do you do this?</h1>
<img id="snip" src="lifeBar.gif">

<h1 class="about question">I have questions, help? Or I have feedback, listen!</h1>

<p class="about text">Tweet us! Email us! Or find us on GitHub (see below)!</p>

<h1 class="about question">By the way, who are you?</h1>

<p class="about text">We are four like-minded coding youngsters with an eye to helping others help themselves answering to the names of: </p>
<ul id="contact">
  <li><a href="http://github.com/lorenanicole">Lorena Mesa</a></li>
  <li><a href="http://github.com/bmurphy1">Brian Murphy</a></li>
  <li><a href="http://github.com/shidel-dev">Joe Shidel</a></li>
  <li><a href="http://github.com/dermatobia">Sara Tansari</a></li>
</ul>

<h1 class="about question">A license you say?</h1>
<p class="about text">Not here. Our code is open source and available on <a id="ourCode" href="https://github.com/shidel-dev/goals-visualization-final-project">GitHub</a>.</p>
</div>
<br><br>

app/views/welcome/index.html.erb
<div id='container'>
  <% if current_user %>
  <%= render partial: "loadlifedata" %>
  <% end %>
  <img id='intro' src="/icons/glyphicons_194_circle_question_mark.png"></img>
  <div class="time">
    <p id="lower" class="time"></p>
    <img class="time" id="past" src="icons/glyphicons_212_down_arrow.png">
    <p id="higher" class="time"></p>
    <img class="time" id="future" src="icons/glyphicons_212_down_arrow.png">
  </div>
  <div id="current_label"><p>This is today</p></div>
  <div id='life_bar'></div>
  <img class='arrow' id="arrow_left" src="arrow_left.png">
  <img class='arrow' id="arrow_right" src="arrow_right.png">
   <div id='legend'>
    <ul>
    <li id='completeLabel'>Complete</li>
    <li id='uncompleteLabel'>To be completed</li>
    </ul>
  </div>
  <div id='time_intervals'>
    <p id="month">month</p>
    <p id="year">year</p>
    <p id="5year">5-year</p>
    <p id="10year">decade</p>
    <p id="life" class='selected'>life</p>
  </div>
    <% if current_user %>
      <br><br>
      <%= link_to "Your Goal Cloud", goals_path, { id: 'goalsPath' } %>
    <% end %>
</div>

<script type="text/template" class='popupTemplate'>
  <div data-id="<%%=v.id%>" class='popup'>
    <div id="head">
    </div>
    <img src="/icons/glyphicons_207_remove_2.png" id='exit'></img>
    <div id="content" placeholder="Enter a goal..." contenteditable="true"><%%= v.title%></div>
    <div id='foot'>
    <img class='action' id='link' src="/icons/glyphicons_422_git_branch.png"></img>


    <img class='action' id='delete' src="/icons/glyphicons_016_bin.png"></img>


    <%% if (v.connections.length){%>
      <img class='action' id='sever' src="/icons/glyphicons_288_scissors.png"></img>
    <%% };$(".action").css("width","33.33%")%>
    <%% if (v.completed){%>
      <img class='action' id='reflection' src="/icons/glyphicons_087_log_book.png"></img>
     <%%}else{%>
      <img class='action' id='complete' src="/icons/glyphicons_206_ok_2.png"></img>
     <%%}%>
    </div>
  </div>

</script>

<script type="text/template" class='reflectionTemplate'>
<div id='modal'>
  <div class='mask closeReflection'>
  </div>
  <div class='reflectionHolder'>
    <h2>Reflection</h2>
    <textarea id="reflectionText" data-id="0" ><%%= v.reflection%></textarea>
    <img class='closeReflection' src='/icons/glyphicons_198_ok.png'></img>
  </div>
</div>
</script>

<script type="text/template" class="goalTitleTemplate">
<div id='titleBubble'><%%= v.title%></div>
</script>

<script type="text/template" class='introTemplate'>
<div id='modal'>
  <div class='mask closeIntro'>
  </div>
  <div class='introHolder'>
    <img class='closeIntro' src='/icons/glyphicons_197_remove.png'></img>
    <h3>Fill you LifeBar with goals, not tasks.</h3>
    <p>Click on your LifebBar to add a goal to a point in your life.</p><br><br>
    <p>You can then click on your goal and add content.</p><br><br>
    <p>Goals can be linked to others to create paths with the linking tool:</p><img class='example' src="/icons/glyphicons_422_git_branch.png"></img><br><br>
    <p>Goals can be completed by clicking the check:</p><img class='example'  src="/icons/glyphicons_206_ok_2.png"></img><br><br>
     <p>Once completed you can use the reflection tool to assess the value of that goal:</p><img class='example'  src="/icons/glyphicons_087_log_book.png"></img><br><br>
    <p>Goals can be removed by using:<img class='example' src="/icons/glyphicons_016_bin.png"></img><br><br>
    <p>Connections can be removed by using:<img class='example'  src="/icons/glyphicons_288_scissors.png"></img></p>

  </div>
</div>
</script>